# Generated by Django 4.0.1 on 2022-01-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lp', models.PositiveSmallIntegerField()),
                ('numer_startowy', models.PositiveSmallIntegerField()),
                ('nazwisko', models.CharField(max_length=40)),
                ('imie', models.CharField(max_length=15)),
                ('kat_wiekowa', models.CharField(max_length=10)),
                ('oplacony', models.BooleanField(default=False)),
                ('bieg', models.CharField(max_length=7)),
                ('data_zapisu', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Zawodnik',
                'verbose_name_plural': 'Zawodnicy',
            },
        ),
    ]
