# Generated by Django 4.0.1 on 2022-01-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='data_zapisu',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
