# Generated by Django 4.0.1 on 2022-01-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_players_data_zapisu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='data_zapisu',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
