# Generated by Django 4.0.1 on 2022-01-27 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_players_data_zapisu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='lp',
        ),
        migrations.AlterField(
            model_name='players',
            name='bieg',
            field=models.CharField(choices=[('A', 'Bieg indywidualny dziecka - 30zł'), ('B', 'Bieg dziecka z rodzicem - 30zł'), ('C', 'Bieg indywidualny dziecka + Bieg dziecka z rodzicem - 50zł')], max_length=90),
        ),
        migrations.AlterField(
            model_name='players',
            name='data_zapisu',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='players',
            name='kat_wiekowa',
            field=models.CharField(choices=[('3 - 4 lata', '3 - 4 lata'), ('5 - 6 lat', '5 - 6 lat'), ('7 - 9 lat', '7 - 9 lat'), ('10 - 12 lat', '10 - 12 lat')], max_length=15),
        ),
    ]
