# Generated by Django 4.0.1 on 2022-01-30 19:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_players_imie_rodzic_players_nazwisko_rodzic'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='email_rodzic',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='telefon_rodzic',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
