# Generated by Django 4.0.1 on 2022-02-04 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0006_players_email_rodzic_players_telefon_rodzic'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='uzytkownik',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
