# Generated by Django 4.0.1 on 2022-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_players_uzytkownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='numer_startowy',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
