# Generated by Django 4.0.1 on 2022-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_players_numer_startowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='miasto',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
