# Generated by Django 4.0.1 on 2022-02-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_players_miasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='godzina_startu',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
