# Generated by Django 4.0.1 on 2022-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_players_godzina_startu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='nazwisko_rodzic',
            field=models.CharField(max_length=40, verbose_name='Nazwisko :'),
        ),
    ]
